version: "3.8"
   
services:
  api:
    image: ice/se-test:latest
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/app/
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:14.2-alpine3.15
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file: .env
